Sample output of 20 runs (with inconsistency)
No Consistency Found
No Consistency Found
No Consistency Found
No Consistency Found
No Consistency Found
Found Inconsistency !
No Consistency Found
No Consistency Found
No Consistency Found
No Consistency Found
No Consistency Found
Found Inconsistency !
Found Inconsistency !
No Consistency Found
No Consistency Found
No Consistency Found
No Consistency Found
No Consistency Found
No Consistency Found
No Consistency Found
